### PR TITLE
update es6-promise to v2.1

### PR DESCRIPTION
**Pull request by coderhaoxin**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
update to v2.1 with `auto polyfill`

https://github.com/jakearchibald/es6-promise/issues/75

**Comment by martinlindhe** [comment]
Could you please also update https://github.com/components/es6-promise/blob/master/bower.json with version "2.1.0" ?

**Comment by coderhaoxin** [comment]
> Could you please also update bower.json with version "2.1.0" ?

done

**Comment by martinlindhe** [comment]
thanks for your contribution!

**Comment by stefanpenner** [comment]
:+1:

**Pull request merged**
